### ISSUE TITLE
When i update comfyui , Loadvideo and videocombine are red now！！！

### ISSUE THREAD

**Issue by QTIGER2** [Kosinkadink/ComfyUI-VideoHelperSuite#101]
When i update comfyui , I also met this problem, My loadvideo and videocombine are red now. And in the comfyui manager,this extension indicate "import failed"!!!

[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg
[VideoHelperSuite] - ERROR - No valid ffmpeg found.
Traceback (most recent call last):
File "/Users/apple/ComfyUI/nodes.py", line 1813, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/Users/apple/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite-main/init.py", line 1, in
from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "/Users/apple/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite-main/videohelpersuite/nodes.py", line 15, in
from .load_video_nodes import LoadVideoUpload, LoadVideoPath
File "/Users/apple/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite-main/videohelpersuite/load_video_nodes.py", line 10, in
from .utils import calculate_file_hash, get_sorted_dir_files_from_directory, get_audio, lazy_eval, is_url
File "/Users/apple/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite-main/videohelpersuite/utils.py", line 50, in
ffmpeg_path = max(ffmpeg_paths, key=ffmpeg_suitability)
ValueError: max() arg is an empty sequence

Cannot import /Users/apple/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite-main module for custom nodes: max() arg is an empty sequence

**Comment by AustinMroz** [comment]
Now this is absolutely related to ffmpeg. Did Video Combine have formats other than "image/webp" or "image/gif" before you updated?

**Comment by QTIGER2** [comment]
Thanks for reply. Before updated,Video Combine have "mp4" "webp” and other options,but i always use "gif",LoadVideo works well too!

I try to reinstall imageio and ffmpeg,but it seems to not work...

> Now this is absolutely related to ffmpeg. Did Video Combine have formats other than "image/webp" or "image/gif" before you updated?

**Comment by AustinMroz** [comment]
That's just the information I was hoping to hear as it confirms ffmpeg was able to be found before the update. I don't have any good guesses currently about what is happening, since the error you're encountering the error before the new code to determine the best available ffmpeg version actually runs, but I'll keep pondering it.

In the meantime, I've pushed a change that should restore access to you for gifs and LoadVideo

**Comment by QTIGER2** [comment]
I  try to reinstall this extension and it just now an it works well again. I dont know what happened.Thanks a lot!!!

> That's just the information I was hoping to hear as it confirms ffmpeg was able to be found before the update. I don't have any good guesses currently about what is happening, since the error you're encountering the error before the new code to determine the best available ffmpeg version actually runs, but I'll keep pondering it.
> 
> In the meantime, I've pushed a change that should restore access to you for gifs and LoadVideo


I  try to reinstall this extension it just now and it works well again. I dont know what happened. Thanks a lot!!!

**Comment by rachelcenter** [comment]
> I try to reinstall this extension it just now and it works well again. I dont know what happened. Thanks a lot!!!
> 
> > That's just the information I was hoping to hear as it confirms ffmpeg was able to be found before the update. I don't have any good guesses currently about what is happening, since the error you're encountering the error before the new code to determine the best available ffmpeg version actually runs, but I'll keep pondering it.
> > In the meantime, I've pushed a change that should restore access to you for gifs and LoadVideo

Can you help me? I'm brand new to this world. when I launch terminal to open ComfyUI it tells me:  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg
[VideoHelperSuite] - ERROR - No valid ffmpeg found.

I saw in the note above that you pushed some kind of update. what do I need to do to get that update? go to "manager"? Please help.

**Comment by rachelcenter** [comment]
i heard you guys mention reinstalling the extension. I tried to go to this website https://[www.ffmpeg.org/download.html#build-mac](url) and I performed:  git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg (within terminal and even though terminal said the install worked), I'm still getting that warning/error about VideoHelperSuite in terminal when I try to boot up comfyUI
